<form action="agregarCategoria" method="POST" class="my-4">
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control">
            </div>
        </div>

        <div class="col-12">
            <div class="form-group">
                <label>Directorio Imagen</label>
                <input required name="img" type="text" class="form-control">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <label>Descripcion</label>
            <textarea name="descripcion" class="form-control" rows="3"></textarea>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>