
<?php require_once 'templates/header.phtml'; ?>

<form action="modificarProducto/<?php echo $producto->id_producto; ?>" method="POST" class="my-4">
    <div class="row">
        <div class="col-8">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control" value="<?php echo $producto->nombre ?>">
            </div>
        </div>
    
        <div class="col-4">
            <div class="form-group">
                <label>Categoría</label>
                <select required name="categoria" class="form-control">
                
                <?php foreach($categorias as $categoria){ ?>
                    <!-- Autocompleto con la seleccionada -->
                    <option value="<?php echo $categoria->id_categoria ?>" <?= $producto->id_categoria == $categoria->id_categoria ? ' selected="selected"' : ''; ?>> 
                        <?php echo $categoria->id_categoria ?> - <?php echo $categoria->nombre ?>
                    </option>
                <?php } ?>
                
                </select>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label>Precio</label>
                <input required name="precio" type="number" class="form-control" value="<?php echo $producto->precio ?>">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>Stock</label>
                <input required name="stock" type="number" class="form-control" value="<?php echo $producto->stock ?>">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>Directorio Imagen</label>
                <input required name="img" type="text" class="form-control" value="<?php echo $producto->imagen ?>">
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Modificar</button>
</form>


<?php require_once 'templates/footer.phtml'; ?>