<?php require 'templates/header.phtml' ?>

<?php require 'templates/form_alta_producto.phtml' ?>

<ul class="list-group">
<?php foreach($productos as $producto){ ?>
    <li class="list-group-item producto-acciones">
        <div>
        <?php echo $producto->nombre ?> | $<?php echo $producto->precio ?></li> <!--como cambio esto -->
        </div>
        <div class="actions">
            <a href="modificar/<?php echo $producto->id_producto ?>?nombre=<?php echo $producto->nombre ?>&?id_categoria=<?php echo $producto->id_categoria ?>" type = "button" class="btn btn-success ml-auto">Modificar</a>
            <a href="eliminar/<?php echo $producto->id_producto ?>" type = "button" class="btn btn-danger ml-auto">Eliminar</a>
        </div>
    </li>
<?php } ?>
</ul>


<?php require 'templates/footer.phtml' ?>
