<?php require 'templates/header.phtml' ?>

<?php if ($isAdmin) { 
    require 'templates/form_alta_categoria.phtml';
} ?>

<ul class="list-group">
<?php foreach($categorias as $categoria){ ?>
    <li class="list-group-item producto-acciones">
        <div class="product-info">
            <div>
                <?php echo $categoria->nombre ?> | <?php echo $categoria->descripcion ?>
            </div>
            <div class="actions">
                <?php if ($isAdmin) { ?>
                    <a href="modificarCategoria/<?php echo $categoria->id_categoria ?>" type="button" class="btn btn-success">Modificar</a>
                    <a href="eliminarCategoria/<?php echo $categoria->id_categoria ?>" type="button" class="btn btn-danger ml-2">Eliminar</a>
                <?php } else { ?>
                    <a href="verCategoria/<?php echo $categoria->id_categoria ?>" type="button" class="btn btn-success">Ver Productos</a>
                <?php } ?>
            </div>
        </div>
    </li>
<?php } ?>
</ul>

<?php require 'templates/footer.phtml' ?>
