<?php require 'templates/header.phtml' ?>

<?php require 'templates/form_alta_categoria.phtml' ?>

<ul class="list-group">
<?php foreach($categorias as $categoria){ ?>
    <li class="list-group-item producto-acciones">
        <div>
        <?php echo $categoria->nombre ?> | <?php echo $categoria->descripcion ?></li>
        </div>
        <div class="actions">
            <a href="modificarCategoria/<?php echo $categoria->id_categoria ?>" type = "button" class="btn btn-success ml-auto">Modificar</a>
            <a href="eliminarCategoria/<?php echo $categoria->id_categoria ?>" type = "button" class="btn btn-danger ml-auto">Eliminar</a>
        </div>
    </li>
<?php } ?>
</ul>


<?php require 'templates/footer.phtml' ?>
