<?php require 'templates/header.phtml' ?>

        <div>
            <h1><?php echo $producto->nombre ?> | $<?php echo $producto->precio ?></h1>
            <h2>Stock: <?php echo $producto->stock?> | Imagen: <?php echo $producto->imagen ?></h2>
            <h3>Categoria: <?php echo $producto->id_categoria ?></h3>
        </div>

        <a href="productos/" class="btn btn-secondary mt-2">Volver</a>

<?php require 'templates/footer.phtml' ?>
