<!-- formulario de alta de tarea -->
<!-- Var dump de producto -->
<?php
    // Obtenemos la URL actual
    $url = $_SERVER['REQUEST_URI'];

    // Descomponemos la URL en segmentos
    $segmentos = explode('/', rtrim($url, '/'));

    // Obtenemos el último segmento
    $id_producto = end($segmentos);


    // Obtengo el nombre para autcompletar el form de productos
    if(isset($_GET['nombre'])){
        $nombre = $_GET['nombre'];
    } else {
        $nombre = '';
    }

    // Obtengo la categoria para autcompletar el form de categorias
    if(isset($_GET['id_categoria'])){
        $id_categoria = $_GET['id_categoria'];
    } else {
        $id_categoria = '';
    }
?>
<?php
    //Obtengo productos
    $categorias = getCategorias();
?>

<form action="modificar/<?php echo $id_producto ?>" method="POST" class="my-4"> <!-- method POST para cuidar el pasaje de información -->
    <div class="row">
        <div class="col-8">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control" value="<?php echo $nombre ?>">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>Categoría</label>
                <select required name="categoria" class="form-control"> <!-- Como soluciono el tema values con la FK -->
                  <!-- loopeo todas las categorias -->

                    <?php foreach($categorias as $categoria){ ?>
                        <option
                            value="<?php echo $categoria->id_categoria ?>">
                            <?php echo $categoria->id_categoria ?> - <?php echo $categoria->nombre ?>
                        </option>
                    <?php } ?>

                <!-- <option value="100">100 - Fútbol</option>
                    <option value="101">101 - Básquet</option>
                    <option value="102">102 - Voley</option> -->
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label>Precio</label>
                <input required name="precio" type="number" class="form-control">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>Stock</label>
                <input required name="stock" type="number" class="form-control">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>Directorio Imagen</label>
                <input required name="img" type="text" class="form-control">
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Modificar</button>
</form>